### ISSUE TITLE
ERROR. wp_safe_redirect fails.

### ISSUE THREAD

**Issue by oschelde** [marioy47/wordpress-multisite-settings#1]
This code has helped me convert a plugin from singlesite to multisite,but after saving an option in sitemeta, I got the following error: "Sorry, you are not allowed to access this page."

To correct the error In the file /includes/class-settings-page.php on line 149, I changed 

from:
network_admin_url( 'settings.php' )
to:
network_admin_url( 'admin.php' ).

**Comment by marioy47** [comment]
It could be a configuration in your multisite since the `settings.php` are the _Network Settings_ page.
